/**
 * DON'T MODIFY OR DELETE THIS SCRIPT (unless you know what you're doing)
 *
 * This script generates the file containing the contracts Abi definitions for Hardhat 3.
 * These definitions are used to derive the types needed in the custom scaffold-eth hooks.
 * This script should run after deployment.
 */

import * as fs from "fs";
import { HardhatRuntimeEnvironment } from "hardhat/types";

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

async function generateDeployedContracts(hre: HardhatRuntimeEnvironment) {
  const TARGET_DIR = "../nextjs/contracts/";
  const ARTIFACTS_DIR = "./artifacts";
  const IGNITION_DIR = "./ignition/deployments";
  
  const allContractsData: Record<string, any> = {};
  
  // Find all chain deployment directories
  const chainDirs = fs.readdirSync(IGNITION_DIR, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory() && dirent.name.startsWith('chain-'))
    .map(dirent => dirent.name);
  
  if (chainDirs.length === 0) {
    console.log("No deployed contracts found. Deploy a contract first.");
    return;
  }
  
  for (const chainDir of chainDirs) {
    const chainId = chainDir.replace('chain-', '');
    const deployedAddressesPath = `${IGNITION_DIR}/${chainDir}/deployed_addresses.json`;
    
    if (!fs.existsSync(deployedAddressesPath)) {
      console.log(`No deployed addresses found for chain ${chainId}`);
      continue;
    }
    
    const deployedAddresses = JSON.parse(fs.readFileSync(deployedAddressesPath, "utf8"));
    const contracts: Record<string, any> = {};
    
    // Process each deployed contract
    for (const [deploymentKey, address] of Object.entries(deployedAddresses)) {
      const [moduleName, contractName] = deploymentKey.split('#');
      
      // Try to find ABI in ignition artifacts first
      const ignitionArtifactPath = `${IGNITION_DIR}/${chainDir}/artifacts/${deploymentKey}.json`;
      let artifact;
      
      if (fs.existsSync(ignitionArtifactPath)) {
        artifact = JSON.parse(fs.readFileSync(ignitionArtifactPath, "utf8"));
      } else {
        // Fallback to regular artifacts
        const artifactPath = `${ARTIFACTS_DIR}/contracts/${contractName}.sol/${contractName}.json`;
        if (fs.existsSync(artifactPath)) {
          artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
        }
      }
      
      if (artifact) {
        contracts[contractName] = {
          address: address,
          abi: artifact.abi,
          transactionHash: "0x..."
        };
        
        console.log(`📝 Added ${contractName} at ${address} for chain ${chainId}`);
      } else {
        console.warn(`⚠️  Artifact not found for ${contractName} (${deploymentKey})`);
      }
    }
    
    if (Object.keys(contracts).length > 0) {
      allContractsData[chainId] = contracts;
    }
  }
  
  // Generate the file content
  const fileContent = Object.entries(allContractsData).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
  }
  
  const finalContent = `${generatedContractComment}
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {${fileContent}} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(`${TARGET_DIR}deployedContracts.ts`, finalContent);
  
  console.log(`📝 Updated TypeScript contract definition file on ${TARGET_DIR}deployedContracts.ts`);
}

// Main function for Hardhat scripts
async function main() {
  const { default: hre } = await import("hardhat");
  await generateDeployedContracts(hre);
}

// Run the script
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

export default generateDeployedContracts;
