/**
 * DON'T MODIFY OR DELETE THIS SCRIPT (unless you know what you're doing)
 *
 * This script generates the file containing the contracts Abi definitions for Hardhat 3.
 * These definitions are used to derive the types needed in the custom scaffold-eth hooks.
 * This script should run after deployment.
 */

import * as fs from "fs";
import { HardhatRuntimeEnvironment } from "hardhat/types";

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

async function generateDeployedContracts(hre: HardhatRuntimeEnvironment) {
  const TARGET_DIR = "../nextjs/contracts/";
  const ARTIFACTS_DIR = "./artifacts";
  
  // Read deployed contracts from Ignition deployments file
  const deploymentsPath = "./ignition/deployments/chain-31337/deployed_addresses.json";
  
  if (!fs.existsSync(deploymentsPath)) {
    console.log("No deployed contracts found. Deploy a contract first.");
    return;
  }
  
  const deployedAddresses = JSON.parse(fs.readFileSync(deploymentsPath, "utf8"));
  
  const deployments = {
    "YourContractModule": {
      "YourContract": {
        type: "contract",
        address: deployedAddresses["YourContractModule#YourContract"]
      }
    }
  };

  const allContractsData: Record<string, any> = {};
  
  // Get chain ID (hardcoded for localhost)
  const chainId = "31337";
  
  const contracts: Record<string, any> = {};
  
  for (const [moduleName, moduleDeployments] of Object.entries(deployments)) {
    for (const [contractName, deployment] of Object.entries(moduleDeployments)) {
      if (deployment.type === "contract") {
        // Read ABI from artifacts
        const artifactPath = `${ARTIFACTS_DIR}/contracts/${contractName}.sol/${contractName}.json`;
        
        if (fs.existsSync(artifactPath)) {
          const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
          
          contracts[contractName] = {
            address: deployment.address,
            abi: artifact.abi,
            transactionHash: deployment.transactionHash || "0x..."
          };
          
          console.log(`📝 Added ${contractName} at ${deployment.address}`);
        } else {
          console.warn(`⚠️  Artifact not found for ${contractName}`);
        }
      }
    }
  }
  
  allContractsData[chainId] = contracts;
  
  // Generate the file content
  const fileContent = Object.entries(allContractsData).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
  }
  
  const finalContent = `${generatedContractComment}
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {${fileContent}} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(`${TARGET_DIR}deployedContracts.ts`, finalContent);
  
  console.log(`📝 Updated TypeScript contract definition file on ${TARGET_DIR}deployedContracts.ts`);
}

// Main function for Hardhat scripts
async function main() {
  const { default: hre } = await import("hardhat");
  await generateDeployedContracts(hre);
}

// Run the script
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

export default generateDeployedContracts;
