/**
 * DON'T MODIFY OR DELETE THIS SCRIPT (unless you know what you're doing)
 *
 * This script generates the file containing the contracts Abi definitions for both Hardhat 2 and 3.
 * These definitions are used to derive the types needed in the custom scaffold-eth hooks.
 * This script should run after deployment.
 */

import * as fs from "fs";
import prettier from "prettier";

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

const DEPLOYMENTS_DIR = "./deployments";
const ARTIFACTS_DIR = "./artifacts";
const IGNITION_DIR = "./ignition/deployments";

function getDirectories(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);
}

function getContractNames(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isFile() && dirent.name.endsWith(".json"))
    .map(dirent => dirent.name.split(".")[0]);
}

function getActualSourcesForContract(sources: Record<string, any>, contractName: string) {
  for (const sourcePath of Object.keys(sources)) {
    const sourceName = sourcePath.split("/").pop()?.split(".sol")[0];
    if (sourceName === contractName) {
      const contractContent = sources[sourcePath].content as string;
      const regex = /contract\s+(\w+)\s+is\s+([^{}]+)\{/;
      const match = contractContent.match(regex);

      if (match) {
        const inheritancePart = match[2];
        const inheritedContracts = inheritancePart.split(",").map(contract => `${contract.trim()}.sol`);
        return inheritedContracts;
      }
      return [];
    }
  }
  return [];
}

function getInheritedFunctions(sources: Record<string, any>, contractName: string) {
  const actualSources = getActualSourcesForContract(sources, contractName);
  const inheritedFunctions = {} as Record<string, any>;

  for (const sourceContractName of actualSources) {
    const sourcePath = Object.keys(sources).find(key => key.includes(`/${sourceContractName}`));
    if (sourcePath) {
      const sourceName = sourcePath?.split("/").pop()?.split(".sol")[0];
      const { abi } = JSON.parse(fs.readFileSync(`${ARTIFACTS_DIR}/${sourcePath}/${sourceName}.json`).toString());
      for (const functionAbi of abi) {
        if (functionAbi.type === "function") {
          inheritedFunctions[functionAbi.name] = sourcePath;
        }
      }
    }
  }

  return inheritedFunctions;
}

function getContractDataFromHardhat2Deployments() {
  if (!fs.existsSync(DEPLOYMENTS_DIR)) {
    return {};
  }
  const output = {} as Record<string, any>;
  const chainDirectories = getDirectories(DEPLOYMENTS_DIR);
  
  for (const chainName of chainDirectories) {
    let chainId;
    try {
      chainId = fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/.chainId`).toString();
    } catch (error) {
      console.log(`No chainId file found for ${chainName}`);
      continue;
    }

    const contracts = {} as Record<string, any>;
    for (const contractName of getContractNames(`${DEPLOYMENTS_DIR}/${chainName}`)) {
      const { abi, address, metadata, receipt } = JSON.parse(
        fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/${contractName}.json`).toString(),
      );
      const inheritedFunctions = metadata ? getInheritedFunctions(JSON.parse(metadata).sources, contractName) : {};
      contracts[contractName] = { 
        address, 
        abi, 
        inheritedFunctions, 
        deployedOnBlock: receipt?.blockNumber,
        transactionHash: receipt?.transactionHash || "0x..."
      };
    }
    output[chainId] = contracts;
  }
  return output;
}

function getContractDataFromHardhat3Ignition() {
  if (!fs.existsSync(IGNITION_DIR)) {
    return {};
  }
  
  const allContractsData: Record<string, any> = {};
  
  // Find all chain deployment directories
  const chainDirs = fs.readdirSync(IGNITION_DIR, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory() && dirent.name.startsWith('chain-'))
    .map(dirent => dirent.name);
  
  for (const chainDir of chainDirs) {
    const chainId = chainDir.replace('chain-', '');
    const deployedAddressesPath = `${IGNITION_DIR}/${chainDir}/deployed_addresses.json`;
    
    if (!fs.existsSync(deployedAddressesPath)) {
      console.log(`No deployed addresses found for chain ${chainId}`);
      continue;
    }
    
    const deployedAddresses = JSON.parse(fs.readFileSync(deployedAddressesPath, "utf8"));
    const contracts: Record<string, any> = {};
    
    // Process each deployed contract
    for (const [deploymentKey, address] of Object.entries(deployedAddresses)) {
      const [moduleName, contractName] = deploymentKey.split('#');
      
      // Try to find ABI in ignition artifacts first
      const ignitionArtifactPath = `${IGNITION_DIR}/${chainDir}/artifacts/${deploymentKey}.json`;
      let artifact;
      
      if (fs.existsSync(ignitionArtifactPath)) {
        artifact = JSON.parse(fs.readFileSync(ignitionArtifactPath, "utf8"));
      } else {
        // Fallback to regular artifacts
        const artifactPath = `${ARTIFACTS_DIR}/contracts/${contractName}.sol/${contractName}.json`;
        if (fs.existsSync(artifactPath)) {
          artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
        }
      }
      
      if (artifact) {
        // Try to get inherited functions from metadata if available
        let inheritedFunctions = {};
        if (artifact.metadata) {
          try {
            const metadata = JSON.parse(artifact.metadata);
            inheritedFunctions = getInheritedFunctions(metadata.sources, contractName);
          } catch (e) {
            console.warn(`Could not parse metadata for ${contractName}`);
          }
        }
        
        contracts[contractName] = {
          address: address,
          abi: artifact.abi,
          inheritedFunctions,
          deployedOnBlock: artifact.receipt?.blockNumber,
          transactionHash: artifact.receipt?.transactionHash || "0x..."
        };
        
        console.log(`📝 Added ${contractName} at ${address} for chain ${chainId}`);
      } else {
        console.warn(`⚠️  Artifact not found for ${contractName} (${deploymentKey})`);
      }
    }
    
    if (Object.keys(contracts).length > 0) {
      allContractsData[chainId] = contracts;
    }
  }
  
  return allContractsData;
}

async function generateDeployedContracts(hre: any) {
  const TARGET_DIR = "../nextjs/contracts/";
  
  // Try Hardhat 2 deployments first, then Hardhat 3 Ignition
  let allContractsData = getContractDataFromHardhat2Deployments();
  
  if (Object.keys(allContractsData).length === 0) {
    allContractsData = getContractDataFromHardhat3Ignition();
  }
  
  if (Object.keys(allContractsData).length === 0) {
    console.log("No deployed contracts found. Deploy a contract first.");
    return;
  }
  
  // Generate the file content
  const fileContent = Object.entries(allContractsData).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
  }
  
  const finalContent = `${generatedContractComment}
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {${fileContent}} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  // Format with Prettier like the original
  const formattedContent = await prettier.format(finalContent, {
    parser: "typescript",
  });

  fs.writeFileSync(`${TARGET_DIR}deployedContracts.ts`, formattedContent);
  
  console.log(`📝 Updated TypeScript contract definition file on ${TARGET_DIR}deployedContracts.ts`);
}

// Main function for Hardhat scripts
async function main() {
  const { default: hre } = await import("hardhat");
  await generateDeployedContracts(hre);
}

// Run the script
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

export default generateDeployedContracts;
